In [ ]:
import pandas as pd
import numpy as np
import glob
from datetime import datetime
import os
import re
import string
import nltk

from collections import Counter
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
file1 = pd.read_csv("/content/drive/MyDrive/IDS 506 Healthcare Analytics/506 Project/Further_filtering/df_ff_11212021.csv")
print(file1.columns)

file1.head()

Index(['Unnamed: 0', 'coordinates', 'created_at', 'hashtags', 'place',
       'source', 'user_id', 'user_description', 'user_name', 'id',
       'user_screen_name', 'user_urls', 'user_verified', 'text', 'ind_org',
       'name_plus_desp', 'name_plus_desp_clean', 'new_col2'],
      dtype='object')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (9,12) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Unnamed: 0,coordinates,created_at,hashtags,place,source,user_id,user_description,user_name,id,user_screen_name,user_urls,user_verified,text,ind_org,name_plus_desp,name_plus_desp_clean,new_col2
0,0,NaN,Sun Nov 21 05:01:57 +0000 2021,NaN,NaN,"<a href=""http://publicize.wp.com/"" rel=""nofoll...",3.064873e+09,"Breaking news, sport, TV, radio and a whole lo...",BalkansTimes.eu,1462285128420544514,BalkansTimesEu,https://www.balkanstimes.eu/,False,Ottawa under fire for changes to COVID-19 bord...,ind,"BalkansTimes.eu Breaking news, sport, TV, radi...",balkanstimeseu breaking news sport tv radio wh...,org
1,1,NaN,Sun Nov 21 05:04:25 +0000 2021,chatwithmark,NaN,"<a href=""http://twitter.com/download/android"" ...",1.272774e+18,#Got7:JB|M|J|JY|YJ|Y|BB|YG| 𓅩 |\nseven or neve...,jelly,1462285749101875202,getdab7,NaN,False,@marktuan #chatwithmark \n\nget i get a hug fr...,ind,jelly #Got7:JB|M|J|JY|YJ|Y|BB|YG| 𓅩 |\nseven o...,jelly got7jbmjjyyjybbyg seven never everever g...,ind
2,2,NaN,Sun Nov 21 05:03:38 +0000 2021,NaN,NaN,"<a href=""http://twitter.com/download/android"" ...",1.448159e+18,NaN,SilverSamurai714,1462285552988786695,SilverSamurai85,NaN,False,@Faceplants00 @RWMaloneMD Why? The testing is ...,ind,NaN,NaN,ind
3,3,NaN,Sun Nov 21 05:02:24 +0000 2021,NaN,NaN,"<a href=""http://twitter.com/download/android"" ...",1.345052e+18,DvidThomsonB,DavidBxxxx,1462285241763069957,ThomsonBreage,NaN,False,She is Miss BJP 2021 Covid19 edition. https://...,ind,DavidBxxxx DvidThomsonB,davidbxxxx dvidthomsonb,ind
4,4,NaN,Sun Nov 21 05:03:34 +0000 2021,NaN,NaN,"<a href=""https://mobile.twitter.com"" rel=""nofo...",1.661808e+09,I want action on climate change. Follows IA no...,whatismore,1462285537075556357,SandraC81413369,NaN,False,@sublimespirit @HelenErrington1 What choice do...,ind,whatismore I want action on climate change. Fo...,whatismore action climate change follows abc l...,ind

In [ ]:
#file1['id'] = file1['id'].astype(float)
file1[file1['id'] == 'agsb_bilbao']

,Unnamed: 0,coordinates,created_at,hashtags,place,source,user_id,user_description,user_name,id,user_screen_name,user_urls,user_verified,text,ind_org,name_plus_desp,name_plus_desp_clean,new_col2
3226,3226,279,1584,3711,ind,NaN,NaN,NaN,NaN,agsb_bilbao,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ind

In [ ]:
file1.dtypes

Unnamed: 0                int64
coordinates              object
created_at               object
hashtags                 object
place                    object
source                   object
user_id                 float64
user_description         object
user_name                object
id                       object
user_screen_name         object
user_urls                object
user_verified            object
text                     object
ind_org                  object
name_plus_desp           object
name_plus_desp_clean     object
new_col2                 object
dtype: object

In [ ]:
#file1[file1[[ 'id', 'text']]['new_col2']=='org']
new_df = file1[file1['new_col2']=='org'][['id', 'text']]
new_df

                        id                                               text
0      1462285128420544514  Ottawa under fire for changes to COVID-19 bord...
68     1462285216836321283  Covid-19 has caused a sense of cultural and in...
88     1462286503145611266  Jammu and Kashmir reported 187 positive cases ...
113    1462286327194341387  NEW DELHI: Over 10 lakh samples were tested fo...
118    1462286155127345153  I hate to inform you but the zoo animals have ...
...                    ...                                                ...
44112  1462647275180675072  HEALTH MINISTRY DATA: Turkey reports 195 coron...
44130  1462647206075256833  #MiddayNews | \n\nStudy, however, has taken a ...
44134  1462647302930120704  9 SSB jawans transferred from West Bengal to D...
44140  1462647370320125959  #Michigan worst #COVID19 hot spot in the natio...
44141  1462646907952631810  Plane carrying doses of COVID-19 vaccines for ...

[2374 rows x 2 columns]

In [ ]:
date1 = '2021-11-21'
date2 = '2021-11-21'
#date2 = '2022-01-31'

mydates = pd.date_range(date1, date2, freq='d')#.tolist()
mydates

DatetimeIndex(['2021-11-21'], dtype='datetime64[ns]', freq='D')

In [ ]:
date1 = '2021-11-21'
date2 = '2022-01-31'

mydates = pd.date_range(date1, date2, freq='d')#.tolist()
print(mydates)
for d in pd.date_range(date1, date2, freq='d'):
  d_str = d.strftime("%m%d%Y")
  print(d_str)

  path = "/content/drive/MyDrive/IDS 506 Healthcare Analytics/506 Project/Further_filtering/df_ff_" + d_str + ".csv"
  df = pd.read_csv(path, engine= 'python')
  df_reduced = df[df['new_col2']=='ind'][['user_id','created_at','id', 'text']]

  path2 = "/content/drive/MyDrive/IDS 506 Healthcare Analytics/506 Project/Only_ind_tweets"

  isExist = os.path.exists(path2)
  if not isExist:
  
    # Create a new directory because it does not exist 
    os.makedirs(path2)
    print("The new directory is created!")
  dest_path = "/content/drive/MyDrive/IDS 506 Healthcare Analytics/506 Project/Only_ind_tweets/df_ind_tweets_" + d_str + ".csv"
  df_reduced.to_csv(dest_path)

DatetimeIndex(['2021-11-21', '2021-11-22', '2021-11-23', '2021-11-24',
               '2021-11-25', '2021-11-26', '2021-11-27', '2021-11-28',
               '2021-11-29', '2021-11-30', '2021-12-01', '2021-12-02',
               '2021-12-03', '2021-12-04', '2021-12-05', '2021-12-06',
               '2021-12-07', '2021-12-08', '2021-12-09', '2021-12-10',
               '2021-12-11', '2021-12-12', '2021-12-13', '2021-12-14',
               '2021-12-15', '2021-12-16', '2021-12-17', '2021-12-18',
               '2021-12-19', '2021-12-20', '2021-12-21', '2021-12-22',
               '2021-12-23', '2021-12-24', '2021-12-25', '2021-12-26',
               '2021-12-27', '2021-12-28', '2021-12-29', '2021-12-30',
               '2021-12-31', '2022-01-01', '2022-01-02', '2022-01-03',
               '2022-01-04', '2022-01-05', '2022-01-06', '2022-01-07',
               '2022-01-08', '2022-01-09', '2022-01-10', '2022-01-11',
               '2022-01-12', '2022-01-13', '2022-01-14', '2022-01-15',
               '2022-01-16', '2022-01-17', '2022-01-18', '2022-01-19',
               '2022-01-20', '2022-01-21', '2022-01-22', '2022-01-23',
               '2022-01-24', '2022-01-25', '2022-01-26', '2022-01-27',
               '2022-01-28', '2022-01-29', '2022-01-30', '2022-01-31'],
              dtype='datetime64[ns]', freq='D')
11212021
11222021
11232021
11242021
11252021
11262021
11272021
11282021
11292021
11302021
12012021
12022021
12032021
12042021
12052021
12062021
12072021
12082021
12092021
12102021
12112021
12122021
12132021
12142021
12152021
12162021
12172021
12182021
12192021
12202021
12212021
12222021
12232021
12242021
12252021
12262021
12272021
12282021
12292021
12302021
12312021
01012022
01022022
01032022
01042022
01052022
01062022
01072022
01082022
01092022
01102022
01112022
01122022
01132022
01142022
01152022
01162022
01172022
01182022
01192022
01202022
01212022
01222022
01232022
01242022
01252022
01262022
01272022
01282022
01292022
01302022
01312022

In [ ]:
p = "/content/drive/MyDrive/IDS 506 Healthcare Analytics/506 Project/Only_ind_tweets/df_ind_tweets_11262021.csv"
df_p = pd.read_csv(p, engine='python')
df_p.columns

Index(['Unnamed: 0', 'user_id', 'created_at', 'id', 'text'], dtype='object')

In [ ]:
'''
date1 = '2021-11-23'
date2 = '2022-01-31'

mydates = pd.date_range(date1, date2, freq='d')#.tolist()
print(mydates)
for d in pd.date_range(date1, date2, freq='d'):
  d_str = d.strftime("%m%d%Y")
  print(d_str)
  path = "/content/drive/MyDrive/IDS 506 Healthcare Analytics/506 Project/Further Filtered/df_ff_" + d_str + ".csv"

  df = pd.read_csv(path, engine= 'python')
  df_reduced = df[df['new_col2']=='ind'][['id', 'text']]

  path2 = "/content/drive/MyDrive/IDS 506 Healthcare Analytics/506 Project/Only_ind_tweets"

  #os.makedirs(path, exist_ok=False)
  isExist = os.path.exists(path2)
  if not isExist:
  
    # Create a new directory because it does not exist 
    os.makedirs(path2)
    print("The new directory is created!")
  dest_path = "/content/drive/MyDrive/IDS 506 Healthcare Analytics/506 Project/Only_ind_tweets/df_ind_tweets_" + d_str + ".csv"
  df_reduced.to_csv(dest_path)

  '''

DatetimeIndex(['2021-11-23', '2021-11-24', '2021-11-25', '2021-11-26',
               '2021-11-27', '2021-11-28', '2021-11-29', '2021-11-30',
               '2021-12-01', '2021-12-02', '2021-12-03', '2021-12-04',
               '2021-12-05', '2021-12-06', '2021-12-07', '2021-12-08',
               '2021-12-09', '2021-12-10', '2021-12-11', '2021-12-12',
               '2021-12-13', '2021-12-14', '2021-12-15', '2021-12-16',
               '2021-12-17', '2021-12-18', '2021-12-19', '2021-12-20',
               '2021-12-21', '2021-12-22', '2021-12-23', '2021-12-24',
               '2021-12-25', '2021-12-26', '2021-12-27', '2021-12-28',
               '2021-12-29', '2021-12-30', '2021-12-31', '2022-01-01',
               '2022-01-02', '2022-01-03', '2022-01-04', '2022-01-05',
               '2022-01-06', '2022-01-07', '2022-01-08', '2022-01-09',
               '2022-01-10', '2022-01-11', '2022-01-12', '2022-01-13',
               '2022-01-14', '2022-01-15', '2022-01-16', '2022-01-17',
               '2022-01-18', '2022-01-19', '2022-01-20', '2022-01-21',
               '2022-01-22', '2022-01-23', '2022-01-24', '2022-01-25',
               '2022-01-26', '2022-01-27', '2022-01-28', '2022-01-29',
               '2022-01-30', '2022-01-31'],
              dtype='datetime64[ns]', freq='D')
11232021
11242021
11252021
11262021
11272021
11282021
11292021
11302021
12012021
12022021
12032021
12042021
12052021
12062021
12072021
12082021
12092021
12102021
12112021
12122021
12132021
12142021
12152021
12162021
12172021
12182021
12192021
12202021
12212021
12222021
12232021
12242021
12252021
12262021
12272021
12282021
12292021
12302021
12312021
01012022
01022022
01032022
01042022
01052022
01062022
01072022
01082022
01092022
01102022
01112022
01122022
01132022
01142022
01152022
01162022
01172022
01182022
01192022
01202022
01212022
01222022
01232022
01242022
01252022
01262022
01272022
01282022
01292022
01302022
01312022

In [ ]:
'''
date1 = '2021-11-21'
date2 = '2021-11-30'

#date1 = datetime.datetime.strptime('12012021', '%m%d%Y')
#date2 = datetime.datetime.strptime('12022021', '%m%d%Y')

mydates = pd.date_range(date1, date2, freq='d')#.tolist()
print(mydates)
for d in pd.date_range(date1, date2, freq='d'):
  d_str = d.strftime("%m%d%Y")
  print(d_str)
  path = "/content/drive/MyDrive/IDS 506 Healthcare Analytics/506 Project/Further Filtered/df_ff_" + d_str + ".csv"

  df = pd.read_csv(path, engine= 'python')
  df_reduced = df[df['new_col2']=='ind'][['id', 'text']]

  nltk.download('punkt')
  nltk.download('stopwords')

  STOP_WORDS = stopwords.words()

  # removing the emojies
  # https://www.kaggle.com/alankritamishra/covid-19-tweet-sentiment-analysis#Sentiment-analysis
  EMOJI_PATTERN = re.compile("["
                            u"\U0001F600-\U0001F64F"  # emoticons
                            u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                            u"\U0001F680-\U0001F6FF"  # transport & map symbols
                            u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                            u"\U00002702-\U000027B0"
                            u"\U000024C2-\U0001F251"
                            "]+", flags=re.UNICODE)


  def cleaning(text):
      """
      Convert to lowercase.
      Rremove URL links, special characters and punctuation.
      Tokenize and remove stop words.
      """
      text = text.lower()
      text = re.sub('https?://\S+|www\.\S+', '', text)
      text = re.sub('@[A-Za-z0-9]+', '', text)
      text = re.sub('<.*?>+', '', text)   # replacing HTML text with blank or whitespace
      text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
      text = re.sub('\n', '', text)
      text = re.sub('[’“”…]', '', text)
      
      text = text.encode("ascii", "ignore")     # consider only english alphanumeric characters
      text = text.decode()
      
      text = EMOJI_PATTERN.sub(r'', text)
    
      
      
      # removing the stop-words
      text_tokens = word_tokenize(text)
      tokens_without_sw = [
        word for word in text_tokens if not word in STOP_WORDS]
      filtered_sentence = (" ").join(tokens_without_sw)
      text = filtered_sentence
      
      return text

  def func2(val1, val2):
    for word in uniq_list:
        if (word in val1):     # may use val2 ie user_verified status for additional filtering
            return "org"
        else:
            return "ind"

  #if __name__ == "__main__":
  #    max_rows = 1000  # 'None' to read whole file
      
  #df = pd.read_csv("Labeled_tweets.csv")
  #df.head()
  df_reduced['name_plus_desp'] = df_reduced['user_name'] + " " + df_reduced['user_description']
  df_reduced['name_plus_desp'] = df_reduced['name_plus_desp'].astype(str)
  df_reduced.head() 
  
  #dt = df_reduced['name_plus_desp'].apply(cleaning)
  df_reduced['name_plus_desp_clean'] = df_reduced['name_plus_desp'].apply(cleaning)
  
  #print(df_reduced['name_plus_desp_clean'])
  print("\n")
  
  # word_count = Counter(" ".join(dt).split()).most_common(10)
  # word_frequency = pd.DataFrame(word_count, columns = ['Word', 'Frequency'])
  # print(word_frequency)
  
  df_reduced['new_col2'] = df_reduced.apply(lambda row: func2(row['name_plus_desp_clean'], row['user_verified']), axis =1)
  print(df_reduced['new_col2'].value_counts())
  
  path2 = "/content/drive/MyDrive/IDS 506 Healthcare Analytics/506 Project/Further_filtering"

  #os.makedirs(path, exist_ok=False)
  isExist = os.path.exists(path2)
  if not isExist:
  
    # Create a new directory because it does not exist 
    os.makedirs(path2)
    print("The new directory is created!")
  dest_path = "/content/drive/MyDrive/IDS 506 Healthcare Analytics/506 Project/Further_filtering/df_ff_" + d_str + ".csv"
  df_reduced.to_csv(dest_path)

'''

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10', '2022-01-11', '2022-01-12',
               '2022-01-13', '2022-01-14', '2022-01-15', '2022-01-16',
               '2022-01-17', '2022-01-18', '2022-01-19', '2022-01-20',
               '2022-01-21', '2022-01-22', '2022-01-23', '2022-01-24',
               '2022-01-25', '2022-01-26', '2022-01-27', '2022-01-28',
               '2022-01-29', '2022-01-30', '2022-01-31'],
              dtype='datetime64[ns]', freq='D')
01012022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:89: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:98: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

ind    65020
org     3731
Name: new_col2, dtype: int64
01022022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    77743
org     4752
Name: new_col2, dtype: int64
01032022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    90970
org     6813
Name: new_col2, dtype: int64
01042022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    107513
org      7547
Name: new_col2, dtype: int64
01052022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    101483
org      7281
Name: new_col2, dtype: int64
01062022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    65724
org     5205
Name: new_col2, dtype: int64
01072022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    110044
org      8526
Name: new_col2, dtype: int64
01082022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    85357
org     5523
Name: new_col2, dtype: int64
01092022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    79093
org     4818
Name: new_col2, dtype: int64
01102022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    94049
org     6996
Name: new_col2, dtype: int64
01112022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    97527
org     7012
Name: new_col2, dtype: int64
01122022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    95631
org     6664
Name: new_col2, dtype: int64
01132022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    96927
org     6803
Name: new_col2, dtype: int64
01142022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    81476
org     5905
Name: new_col2, dtype: int64
01152022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    61407
org     3758
Name: new_col2, dtype: int64
01162022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    55234
org     3324
Name: new_col2, dtype: int64
01172022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    61570
org     4625
Name: new_col2, dtype: int64
01182022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    77712
org     5853
Name: new_col2, dtype: int64
01192022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    77323
org     6003
Name: new_col2, dtype: int64
01202022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    59684
org     4548
Name: new_col2, dtype: int64
01212022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    63409
org     5002
Name: new_col2, dtype: int64
01222022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    52620
org     3513
Name: new_col2, dtype: int64
01232022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    49291
org     3056
Name: new_col2, dtype: int64
01242022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    66294
org     4351
Name: new_col2, dtype: int64
01252022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    65244
org     4636
Name: new_col2, dtype: int64
01262022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    58275
org     4076
Name: new_col2, dtype: int64
01272022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    63776
org     4136
Name: new_col2, dtype: int64
01282022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    60319
org     3932
Name: new_col2, dtype: int64
01292022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    47464
org     3062
Name: new_col2, dtype: int64
01302022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    44354
org     2660
Name: new_col2, dtype: int64
01312022
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


ind    66021
org     4744
Name: new_col2, dtype: int64

In [ ]:

'''

def func2(val1, val2):
    for word in uniq_list:
        if (word in val1):     # may use val2 ie user_verified status for additional filtering
            return "org"
        else:
            return "ind"

df_reduced['new_col2'] = df_reduced.apply(lambda row: func2(row['name_plus_desp_clean'], row['user_verified']), axis =1)
'''